### ISSUE TITLE
Cannot find module '/root/.pm2/node_modules/pm2-server-monit/package.json'

### ISSUE THREAD

**Issue by danmasta** [pm2-hive/pm2-server-monit#54]
Tried installing server-monit from both the dashboard and command line and keep getting this error. Searched around and couldn't find a solution. Any idea how to fix this and get server-monit installed?

```
root@server:~# pm2 install pm2-server-monit
[PM2][Module] Installing module pm2-server-monit
[PM2][Module] Calling [NPM] to install pm2-server-monit ...
/root
└── pm2-server-monit@2.5.1

[PM2][Module] Module downloaded
module.js:471
    throw err;
    ^

Error: Cannot find module '/root/.pm2/node_modules/pm2-server-monit/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at startModule (/usr/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:33:22)
    at /usr/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:158:9
    at /usr/lib/node_modules/pm2/lib/Configuration.js:64:14
    at FSReqWrap.oncomplete (fs.js:123:15)
root@server:~#
```
```
node: v6.9.4
npm: v3.10.10
os: Ubuntu 16.04
```

**Comment by jenguidanos** [comment]
I had the same problem. Solved manually editing `/usr/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:33:22`  because the path to `[...]/node_modules/pm2-server-monit/package.json` was incorrect.

I know editing this file is not a clean solution. On the named file (pm2/lib/API/Modules/Modularizer.js) the property opts.cmd has an incorrect value. I don't know how to pass this argument when calling "pm2 install pm2-server-monit" to set the correct value on `opts.cmd`.

The problem also accours with other modules, like pm2-mongodb. In this case fails because "Cannot find module '/home/rhomb/.pm2/node_modules/**pm2-mongodb**/package.json'".

**Comment by f-hj** [comment]
PM2 related
https://github.com/Unitech/pm2/issues
